#!/bin/sh

# vgncontentindex
#
# Shell script to run the content index tool.
#
# Assumptions:
#  1) We are using ./setupcfgenv to determine our runtime environment.
#  2) Thirdparty/shared jar files are in the ./lib directory.
#     Run 'vgncontentindex -?' for more details.

PRG="`command type $0 | cut -d' ' -f3-`" >/dev/null 2>&1
J_HOME=`dirname $PRG`/../jre

if [ "$OS" = "Windows_NT" ]
  then SEP=";"
else SEP=":"
fi


BINDIR="`dirname $PRG`"

. $BINDIR/setupcfgenv.sh

CLASSDIR=$BINDIR/../lib

# vgn jar files
CP=$CLASSDIR
CP=$CP$SEP$CLASSDIR/autonomyClient.jar
CP=$CP$SEP$CLASSDIR/jsafe.jar
CP=$CP$SEP$CLASSDIR/log4j.jar
CP=$CP$SEP$CLASSDIR/vgn-shared-logging.jar
CP=$CP$SEP$CLASSDIR/vgncommon.jar
CP=$CP$SEP$CLASSDIR/vgnssl.jar
CP=$CP$SEP$CLASSDIR/vgn-appsvcs-combined.jar
CP=$CP$SEP$CLASSDIR/vgn-appsvcs-config.jar
CP=$CP$SEP$CLASSDIR/vgnhpdapi-8.0.jar
CP=$CP$SEP$CLASSDIR/commons-httpclient.jar
CP=$CP$SEP$CLASSDIR/commons-logging.jar
CP=$CP$SEP$CLASSDIR/commons-codec.jar
CP=$CP$SEP$CLASSDIR/commons-dbcp.jar
CP=$CP$SEP$CLASSDIR/castor-0.9.3.9.jar
CP=$CP$SEP$CLASSDIR/sdk/vgn-appsvcs-cda.jar
CP=$CP$SEP$CLASSDIR/apache-solr-cell.jar
CP=$CP$SEP$CLASSDIR/apache-solr-solrj.jar
CP=$CP$SEP$CLASSDIR/solr-slf4j-api.jar
CP=$CP$SEP$CLASSDIR/solr-slf4j-jdk14.jar
CP=$CP$SEP$CLASSDIR/apache-httpclient.jar
CP=$CP$SEP$CLASSDIR/apache-httpcore.jar
CP=$CP$SEP$CLASSDIR/apache-httpmime.jar
CP=$CP$SEP$CLASSDIR/jackson-core.jar

CP=$CP$SEP$CLASSDIR/wem-nstein.jar
CP=$CP$SEP/opentext/otwork/WEM/Extensions/Extension_Nstein/src/config/
# JDBC drivers
JDBCDIR=$BINDIR/../jdbc
CP=$CP$SEP$JDBCDIR/ojdbc6.jar
CP=$CP$SEP$JDBCDIR/ojdbc5.jar
CP=$CP$SEP$JDBCDIR/vgnjdbc.jar
CP=$CP$SEP.
CP=$CP$SEP$BINDIR/.
CP=$CP$SEP$CLASSPATH


exec $JAVAPROG $JAVAARGS -cp $CP -Xmx512m com.opentext.demo.otsn.apps.contentIndex.ContentIndexDriver "$@"
