language: java
os: linux
dist: trusty
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "openturing"
    token: ${SONAR_TOKEN}
script:
  - ./gradlew check
  -  sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)